name: MyActions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-editor:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clone repository
      uses: actions/checkout@v1 
      
    - name: install 
      run : pip install -r requirements.txt
      
    - name: fix
      run : black ./ && isort ./ && flake8 ./
      
    

    


      
      
      
    

