name: GitHub-Actions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: black
      run: black --check ./
    - name: flake8
      run: flake8 ./
    - name: isort
      run: isort --check-only ./
    - name: print
      run: echo 'Complete check files'
      
  fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: black
      run: black ./
    - name: flake8
      run: flake8 ./
    - name: isort
      run: isort ./
    - name: print
      run: echo 'Complete fix files'
      
      
      
    

