name: GitHub-Actions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  editor:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Clone repository
      uses: actions/checkout@v1 
      
    - name: check
      run : black --check ./ && isort --check-only ./ && flake8 ./
      
    - name: fix
      run : black ./ && isort ./ && flake8 ./
    

    


      
      
      
    

