name: Fix code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
           python-version: "3.10"
      - name: Install
        run: pip install -r requirements.txt
      - name: Check
        run: flake8 ./
      - name: Fix
        run: black --check ./ && isort --check-only ./
