name: GitHub-Actions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_1:
    runs-on: ubuntu-latest
    
    steps:
    - name: print_1
      run: echo "Hello GitHub Actions!"
      
  test_2:
    runs-on: ubuntu-latest
    
    steps:
    - name: print_2
      run: echo "Nice work!"

      
      
      
    

